language: python

sudo: false

install:
  - travis_retry python setup.py install
  - pip install coveralls

jobs:
  include:
    - name: "Tests: python 3.5"
      python: 3.5
      script:
        - coverage run --source=betfairlightweight setup.py test
    - name: "Tests: python 3.6"
      python: 3.6
      script:
        - coverage run --source=betfairlightweight setup.py test
    - name: "Tests: python 3.7"
      python: 3.7
      dist: xenial
      script:
        - coverage run --source=betfairlightweight setup.py test
    - name: "Tests: python 3.8"
      python: 3.8
      dist: xenial
      script:
        - coverage run --source=betfairlightweight setup.py test
    - name: "Tests: python 3.9"
      python: 3.9
      dist: xenial
      script:
        - coverage run --source=betfairlightweight setup.py test
    - name: "Lint: python 3.7"
      python: 3.7
      dist: xenial
      install:
        - pip install black
      script:
        - black --check --diff .

after_success:
  coveralls
