build: off

environment:
  matrix:
    - PYTHON: "C:\\Python35"
      PYTHON_VERSION: "3.5.x"

    - PYTHON: "C:\\Python36"
      PYTHON_VERSION: "3.6.x"

    - PYTHON: "C:\\Python37"
      PYTHON_VERSION: "3.7.x"

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "pip install setuptools==39.2.0"
  - "python setup.py install"

test_script:
  - "python setup.py test"
